# If you want to use a different version of CUDA, view the available
# images here: https://hub.docker.com/r/nvidia/cuda
# Note:
#   - Jax currently supports CUDA versions up to 11.3.
#   - Tensorflow required CUDA versions after 11.2.
ARG cuda_docker_tag="12.8.0-cudnn-devel-ubuntu24.04"
FROM nvidia/cuda:${cuda_docker_tag}
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade -y

# tzdata is required below. To avoid hanging, install it first.
RUN apt install tzdata -y
RUN apt install git \
    wget \
    # libgl1-mesa-glx \
    software-properties-common \
    vim \
    gcc \
    ssh \
    libx11-dev \
    xorg \
    curl \
    -y

# Install python3.10.
RUN add-apt-repository ppa:deadsnakes/ppa -y
RUN apt update --fix-missing -y
RUN apt install \
    python3.12 \
    python3.12-dev \
    python3.12-venv \
    -y


# Make python3.10 the default python.
RUN rm /usr/bin/python3
RUN ln -s /usr/bin/python3.12 /usr/bin/python3
RUN ln -s /usr/bin/python3.12 /usr/bin/python

# Create venv
RUN mkdir /root/.venv
WORKDIR /root/.venv
RUN python3.12 -m venv sam3_env

# Install MuJoCo Python Bindings
RUN apt update -y

# Install PyTorch
RUN . /root/.venv/sam3_env/bin/activate && \
    pip install \
    torch \
    torchaudio \
    torchvision \
    --index-url https://download.pytorch.org/whl/cu128

# RUN pip install setuptools
RUN . /root/.venv/sam3_env/bin/activate && \
    pip install \
    swig \
    imageio 

# Install other Python Deps
RUN . /root/.venv/sam3_env/bin/activate && \
    pip install \
    matplotlib \
    # box2d-py \
    numpy \
    pandas \
    # seaborn \
    PyQt5

# Add SAM
ADD sam3 /root/sam3
WORKDIR /root/sam3
RUN . /root/.venv/sam3_env/bin/activate && \
    pip install -e .

RUN echo ". /root/.venv/sam3_env/bin/activate" >> ~/.bashrc